Tool changes
EasyMeshVR/EasyMeshVR-Prototype pull request #66
Opened 2022-04-13 00:18 UTC by DTilley22

Tool Class
-Added input detection for right trigger

Extrude
- Added letting go of secondary extrusion using the trigger
- Added locking new gameObjects that are connected to locked vertices

Lock Vertex

- All faces and edges attached to a vertex will also be locked/unlocked

Axis Lock

- To use enable it in the editor and enable the isActive boolean, its attached to RightRadius with the other tools
- Only works on vertices and faces
- Lock to an axis by pressing the primary button while hovering over an object, when its grabbed it will only move along that axis
- Press secondary button to unlock and reset cycle
- Axis order is X, Y, Z

Issues

- Lock Axis needs UI for enabling if we include it
- Can't cycle through axes without moving the object first
- Edges always drift when using Lock Axis so for now it only works with vertices and faces
- Tried extending Lock Vertex to locking edges and faces as well but it doesn't work I think because of the network script, the code is in the other branch
- Not sure if anything needs to edited for multiplayer
- Undoing then redoing extrusion with new locked edges and faces unlocks them

2022-04-13 00:43 UTC, Rami-J commented on Assets/Scripts/Tools/LockVertex.cs
> +        foreach(Edge e in meshRebuilder.edgeObjects)
couldn't you go through the vertex's connectedFaces and connectedEdges array instead of all the edges/faces?

2022-04-13 00:43 UTC, Rami-J commented on Assets/Scripts/Tools/LockVertex.cs
> +        foreach(Edge e in meshRebuilder.edgeObjects)
here as well

2022-04-13 00:43 UTC, Rami-J commented on Assets/Scripts/Tools/Extrude.cs
> +        foreach(Edge e in meshRebuilder.edgeObjects)
instead, try going through the connectedFaces/connectedEdges lists on the Vertex object see if that works

2022-04-13 01:08 UTC, DTilley22 commented
@Rami-J 
It works for LockVertex but not for Extrude because the new edges and faces aren't being added to old vertices

2022-04-13 01:41 UTC, DTilley22 commented
@Rami-J 
Added caching new edges and faces in latest commit, should work with both now
Merge still has problems with extrusion though

2022-04-13 04:57 UTC, Rami-J commented
i'll test this on multiplayer tomorrow

2022-04-13 18:17 UTC, Rami-J commented
![image](https://user-images.githubusercontent.com/44623786/163244566-508c80c0-c18a-4671-bcb1-5b26d832838e.png)
there's an error when opening the game menu

2022-04-13 18:23 UTC, Rami-J commented
have you tested undo/redo with extrude? it logs errors in the console for me

2022-04-13 20:14 UTC, DTilley22 commented
> have you tested undo/redo with extrude? it logs errors in the console for me

Yeah with extruding undoing/redoing only happens once, getting rid of the new code makes it work
extruding both triangles of a face then undoing breaks it because the shared vertices are getting removed but this already happens on main

2022-04-13 20:28 UTC, DTilley22 commented
@Rami-J See if the new commit fixes it

2022-04-13 20:51 UTC, Rami-J commented
I tried it in multiplayer, no errors encountered anymore

2022-04-13 20:52 UTC, Rami-J approved these changes

2022-04-13 23:05 UTC, DTilley22 commented
@Rami-J
Turns out the new functions weren't being called
Extruding on a newly extruded face is the issue, it looks like extruding any of the original faces works fine with undo/redo

2022-04-13 23:38 UTC, DTilley22 commented
It should work now, it looks like connectedFaces contains null objects but I just edited extrudeOp to ignore them for now

2022-04-14 01:26 UTC, Rami-J approved these changes

2022-04-14 01:28 UTC, Rami-J commented
still need to test in multiplayer but looks like it works in singleplayer

2022-04-14 01:30 UTC, Rami-J commented
nvm, it crashes in multiplayer when rejoining a room that had an extrusion in it for some reason 
![image](https://user-images.githubusercontent.com/44623786/163296173-a49b3bd0-f1ec-4b0a-ba0b-a5c1df5a553a.png)

2022-04-14 01:52 UTC, Rami-J commented
i pushed a commit that i thought would fix it but i think it has to do with the vertice ids attached to the face object going out of bounds

2022-04-14 02:06 UTC, Rami-J requested changes
Bug: Deexecute() function in ExtrudeOp crashes when it tries to go through connectedFaces for the vertices generated by the extrude operation when rejoining a room with an extrusion operation in it (goes out of bounds of the meshRebuilder.vertexObjects array). Last time I checked this didn't occur on main, so it might have been something added on this PR

2022-04-14 03:18 UTC, Rami-J commented
I think I ended up preventing the error altogether by checking to make sure the index wasn't out of bounds, but I suspect the new connectOldVerts() may have introduced bad vertex IDs/connections somehow, temporary fix for now

2022-04-14 05:56 UTC, DTilley22 commented
Commented out calls to connecting old vertices since I only implemented them to see if merge would work and to make locking new objects easier, rewrote locking new objects to only loop through recently added triangles

2022-04-14 21:59 UTC, Rami-J approved these changes

2022-04-17 02:39 UTC, merged